<Project Sdk="Godot.NET.Sdk/4.2.2">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <RootNamespace>Corpo</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\CorpoFs\CorpoFs.fsproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <PackageReference Include="Serilog" Version="4.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
    </ItemGroup>
    <ItemGroup>
      <Compile Include="..\..\addons\GDTask\AsyncLazy.cs">
        <Link>addons\GDTask\AsyncLazy.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\AsyncUnit.cs">
        <Link>addons\GDTask\AsyncUnit.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Autoload\GDTaskPlayerLoopAutoload.cs">
        <Link>addons\GDTask\Autoload\GDTaskPlayerLoopAutoload.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Autoload\ProcessListener.cs">
        <Link>addons\GDTask\Autoload\ProcessListener.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\CancellationTokenEqualityComparer.cs">
        <Link>addons\GDTask\CancellationTokenEqualityComparer.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\CancellationTokenExtensions.cs">
        <Link>addons\GDTask\CancellationTokenExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\CancellationTokenSourceExtensions.cs">
        <Link>addons\GDTask\CancellationTokenSourceExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\CompilerServices\AsyncGDTaskMethodBuilder.cs">
        <Link>addons\GDTask\CompilerServices\AsyncGDTaskMethodBuilder.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\CompilerServices\AsyncGDTaskVoidMethodBuilder.cs">
        <Link>addons\GDTask\CompilerServices\AsyncGDTaskVoidMethodBuilder.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\CompilerServices\StateMachineRunner.cs">
        <Link>addons\GDTask\CompilerServices\StateMachineRunner.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.cs">
        <Link>addons\GDTask\GDTask.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.Delay.cs">
        <Link>addons\GDTask\GDTask.Delay.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.Factory.cs">
        <Link>addons\GDTask\GDTask.Factory.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.Run.cs">
        <Link>addons\GDTask\GDTask.Run.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.Threading.cs">
        <Link>addons\GDTask\GDTask.Threading.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.ToSignal.cs">
        <Link>addons\GDTask\GDTask.ToSignal.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.WaitUntil.cs">
        <Link>addons\GDTask\GDTask.WaitUntil.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.WhenAll.cs">
        <Link>addons\GDTask\GDTask.WhenAll.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.WhenAll.Generated.cs">
        <Link>addons\GDTask\GDTask.WhenAll.Generated.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.WhenAny.cs">
        <Link>addons\GDTask\GDTask.WhenAny.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTask.WhenAny.Generated.cs">
        <Link>addons\GDTask\GDTask.WhenAny.Generated.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskCompletionSource.cs">
        <Link>addons\GDTask\GDTaskCompletionSource.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskExtensions.cs">
        <Link>addons\GDTask\GDTaskExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskExtensions.Shorthand.cs">
        <Link>addons\GDTask\GDTaskExtensions.Shorthand.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskObservableExtensions.cs">
        <Link>addons\GDTask\GDTaskObservableExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskScheduler.cs">
        <Link>addons\GDTask\GDTaskScheduler.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskSynchronizationContext.cs">
        <Link>addons\GDTask\GDTaskSynchronizationContext.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\GDTaskVoid.cs">
        <Link>addons\GDTask\GDTaskVoid.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\IGDTaskSource.cs">
        <Link>addons\GDTask\IGDTaskSource.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\ArrayPool.cs">
        <Link>addons\GDTask\Internal\ArrayPool.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\ArrayPoolUtil.cs">
        <Link>addons\GDTask\Internal\ArrayPoolUtil.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\ArrayUtil.cs">
        <Link>addons\GDTask\Internal\ArrayUtil.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\ContinuationQueue.cs">
        <Link>addons\GDTask\Internal\ContinuationQueue.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\DiagnosticsExtensions.cs">
        <Link>addons\GDTask\Internal\DiagnosticsExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\Error.cs">
        <Link>addons\GDTask\Internal\Error.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\GodotEqualityComparer.cs">
        <Link>addons\GDTask\Internal\GodotEqualityComparer.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\MinimumQueue.cs">
        <Link>addons\GDTask\Internal\MinimumQueue.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\PlayerLoopRunner.cs">
        <Link>addons\GDTask\Internal\PlayerLoopRunner.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\PooledDelegate.cs">
        <Link>addons\GDTask\Internal\PooledDelegate.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\RuntimeHelpersAbstraction.cs">
        <Link>addons\GDTask\Internal\RuntimeHelpersAbstraction.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\StatePool.cs">
        <Link>addons\GDTask\Internal\StatePool.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\TaskTracker.cs">
        <Link>addons\GDTask\Internal\TaskTracker.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\ValueStopwatch.cs">
        <Link>addons\GDTask\Internal\ValueStopwatch.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Internal\WeakDictionary.cs">
        <Link>addons\GDTask\Internal\WeakDictionary.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\MoveNextSource.cs">
        <Link>addons\GDTask\MoveNextSource.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\PlayerLoopTimer.cs">
        <Link>addons\GDTask\PlayerLoopTimer.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Progress.cs">
        <Link>addons\GDTask\Progress.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\TaskPool.cs">
        <Link>addons\GDTask\TaskPool.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\TimeoutController.cs">
        <Link>addons\GDTask\TimeoutController.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\TriggerEvent.cs">
        <Link>addons\GDTask\TriggerEvent.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Triggers\AsyncDestroyTrigger.cs">
        <Link>addons\GDTask\Triggers\AsyncDestroyTrigger.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Triggers\AsyncEnterTreeTrigger.cs">
        <Link>addons\GDTask\Triggers\AsyncEnterTreeTrigger.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Triggers\AsyncReadyTrigger.cs">
        <Link>addons\GDTask\Triggers\AsyncReadyTrigger.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Triggers\AsyncTriggerBase.cs">
        <Link>addons\GDTask\Triggers\AsyncTriggerBase.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Triggers\AsyncTriggerExtensions.cs">
        <Link>addons\GDTask\Triggers\AsyncTriggerExtensions.cs</Link>
      </Compile>
      <Compile Include="..\..\addons\GDTask\Triggers\NodeMessagesTriggers.cs">
        <Link>addons\GDTask\Triggers\NodeMessagesTriggers.cs</Link>
      </Compile>
      <Compile Include="..\BuildTools\dist\csharp\json\PackageMetadataJson.cs">
        <Link>csharp\json\PackageMetadataJson.cs</Link>
      </Compile>
      <Compile Include="..\BuildTools\dist\csharp\json\PackagesJson.cs">
        <Link>csharp\json\PackagesJson.cs</Link>
      </Compile>
      <Compile Include="..\BuildTools\dist\csharp\json\SettingsJson.cs">
        <Link>csharp\json\SettingsJson.cs</Link>
      </Compile>
    </ItemGroup>
    <ItemGroup>
      <Content Include="..\..\addons\.editorconfig">
        <Link>addons\.editorconfig</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\COMMIT_EDITMSG">
        <Link>addons\GDTask\.git\COMMIT_EDITMSG</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\config">
        <Link>addons\GDTask\.git\config</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\description">
        <Link>addons\GDTask\.git\description</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\HEAD">
        <Link>addons\GDTask\.git\HEAD</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\applypatch-msg.sample">
        <Link>addons\GDTask\.git\hooks\applypatch-msg.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\commit-msg.sample">
        <Link>addons\GDTask\.git\hooks\commit-msg.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\fsmonitor-watchman.sample">
        <Link>addons\GDTask\.git\hooks\fsmonitor-watchman.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\post-update.sample">
        <Link>addons\GDTask\.git\hooks\post-update.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\pre-applypatch.sample">
        <Link>addons\GDTask\.git\hooks\pre-applypatch.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\pre-commit.sample">
        <Link>addons\GDTask\.git\hooks\pre-commit.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\pre-merge-commit.sample">
        <Link>addons\GDTask\.git\hooks\pre-merge-commit.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\pre-push.sample">
        <Link>addons\GDTask\.git\hooks\pre-push.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\pre-rebase.sample">
        <Link>addons\GDTask\.git\hooks\pre-rebase.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\pre-receive.sample">
        <Link>addons\GDTask\.git\hooks\pre-receive.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\prepare-commit-msg.sample">
        <Link>addons\GDTask\.git\hooks\prepare-commit-msg.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\push-to-checkout.sample">
        <Link>addons\GDTask\.git\hooks\push-to-checkout.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\hooks\update.sample">
        <Link>addons\GDTask\.git\hooks\update.sample</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\index">
        <Link>addons\GDTask\.git\index</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\info\exclude">
        <Link>addons\GDTask\.git\info\exclude</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\logs\HEAD">
        <Link>addons\GDTask\.git\logs\HEAD</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\logs\refs\heads\master">
        <Link>addons\GDTask\.git\logs\refs\heads\master</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\05\895288d6a62e9b87d3d7127f9e7583eb5f8982">
        <Link>addons\GDTask\.git\objects\05\895288d6a62e9b87d3d7127f9e7583eb5f8982</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\0c\344ec2f361d90d8403cd12c458706c46c85712">
        <Link>addons\GDTask\.git\objects\0c\344ec2f361d90d8403cd12c458706c46c85712</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\0e\0c1a92f8cfbaba22c56b58cd2775c19465551b">
        <Link>addons\GDTask\.git\objects\0e\0c1a92f8cfbaba22c56b58cd2775c19465551b</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\12\5bc7612f6a6c76f11833c4e1c353b1e1b2e1e9">
        <Link>addons\GDTask\.git\objects\12\5bc7612f6a6c76f11833c4e1c353b1e1b2e1e9</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\14\2533b2ff4522dbb821832403f040e3188fe088">
        <Link>addons\GDTask\.git\objects\14\2533b2ff4522dbb821832403f040e3188fe088</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\14\755e0d890fe61b4154e337b6542a4490cbb51d">
        <Link>addons\GDTask\.git\objects\14\755e0d890fe61b4154e337b6542a4490cbb51d</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\15\66d913216b0cb44d5dd1a32820b0e9e3a2cac4">
        <Link>addons\GDTask\.git\objects\15\66d913216b0cb44d5dd1a32820b0e9e3a2cac4</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\16\78fd3ff395dc28081156563950b8bf703d4fbd">
        <Link>addons\GDTask\.git\objects\16\78fd3ff395dc28081156563950b8bf703d4fbd</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\16\ed2f243bc05fdf78bf78ad2eafb6905baf7749">
        <Link>addons\GDTask\.git\objects\16\ed2f243bc05fdf78bf78ad2eafb6905baf7749</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\17\19f31ecb6cb39c990ddfbd52420a555beba32f">
        <Link>addons\GDTask\.git\objects\17\19f31ecb6cb39c990ddfbd52420a555beba32f</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\1e\9cf49b07593742bb9e06752849b160e58ce99a">
        <Link>addons\GDTask\.git\objects\1e\9cf49b07593742bb9e06752849b160e58ce99a</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\24\8a78ec14ffe381b6453c243e78e97cc6c3ba86">
        <Link>addons\GDTask\.git\objects\24\8a78ec14ffe381b6453c243e78e97cc6c3ba86</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\35\2a7c5e5792c2d49e8c703b5ee27d71854a8e3f">
        <Link>addons\GDTask\.git\objects\35\2a7c5e5792c2d49e8c703b5ee27d71854a8e3f</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\35\852bb1791b2fcc3615614ab5514cf8c5551814">
        <Link>addons\GDTask\.git\objects\35\852bb1791b2fcc3615614ab5514cf8c5551814</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\3b\0ef7425c9cdca700ea3706d84813354289fb01">
        <Link>addons\GDTask\.git\objects\3b\0ef7425c9cdca700ea3706d84813354289fb01</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\3c\063c1664492176ba25df13bb423f4e8861ec16">
        <Link>addons\GDTask\.git\objects\3c\063c1664492176ba25df13bb423f4e8861ec16</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\3e\56da18abdc71ea5e24d03f0078ef02b117d1a7">
        <Link>addons\GDTask\.git\objects\3e\56da18abdc71ea5e24d03f0078ef02b117d1a7</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\48\2857c8f86ecf3d4e840bcb8f651de182a3a82a">
        <Link>addons\GDTask\.git\objects\48\2857c8f86ecf3d4e840bcb8f651de182a3a82a</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\4a\aec59e06346ed651041a13796eb886656d62ab">
        <Link>addons\GDTask\.git\objects\4a\aec59e06346ed651041a13796eb886656d62ab</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\4e\7d8d377f192b2da94c29feeb7dbb67283ded1e">
        <Link>addons\GDTask\.git\objects\4e\7d8d377f192b2da94c29feeb7dbb67283ded1e</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\4e\c588656c48e2e9884efa7f09a834fa839cad31">
        <Link>addons\GDTask\.git\objects\4e\c588656c48e2e9884efa7f09a834fa839cad31</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\56\0ec69102c3acb04893c8045a1650a32b2b99b5">
        <Link>addons\GDTask\.git\objects\56\0ec69102c3acb04893c8045a1650a32b2b99b5</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\56\c4067324b225c29335234e69ac436ec701a83e">
        <Link>addons\GDTask\.git\objects\56\c4067324b225c29335234e69ac436ec701a83e</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\59\4b74eaf883bec67429eb99380ec79a8fd33541">
        <Link>addons\GDTask\.git\objects\59\4b74eaf883bec67429eb99380ec79a8fd33541</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\5e\dd98f1b0301105371d02496e90dcb37b64d160">
        <Link>addons\GDTask\.git\objects\5e\dd98f1b0301105371d02496e90dcb37b64d160</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\5f\89e0fa43f8d0af41daa81f71a4652f8a6e1071">
        <Link>addons\GDTask\.git\objects\5f\89e0fa43f8d0af41daa81f71a4652f8a6e1071</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\60\1177ab5308a09bb0f758996c388ec93597bac8">
        <Link>addons\GDTask\.git\objects\60\1177ab5308a09bb0f758996c388ec93597bac8</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\64\28bc33c55487cda00d8b27b6cabb10e28bf63f">
        <Link>addons\GDTask\.git\objects\64\28bc33c55487cda00d8b27b6cabb10e28bf63f</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\67\558dc9c0f69609a249a8ced0b4790eb2046bbc">
        <Link>addons\GDTask\.git\objects\67\558dc9c0f69609a249a8ced0b4790eb2046bbc</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\68\ab6ed8681b93ac9c1a860423d07eeb858403c3">
        <Link>addons\GDTask\.git\objects\68\ab6ed8681b93ac9c1a860423d07eeb858403c3</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\6c\d0e1d7c46001aa4cad311a25f0ac126a4b222a">
        <Link>addons\GDTask\.git\objects\6c\d0e1d7c46001aa4cad311a25f0ac126a4b222a</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\72\2549d4d0e4a30a1a963ce8faa4407656afca3e">
        <Link>addons\GDTask\.git\objects\72\2549d4d0e4a30a1a963ce8faa4407656afca3e</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\76\fb34e8c3908fd1ff099f44c40d8a97b5a5cd95">
        <Link>addons\GDTask\.git\objects\76\fb34e8c3908fd1ff099f44c40d8a97b5a5cd95</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\8b\f55994ab33df3e09fe4e0d96dfdea4eb3accb3">
        <Link>addons\GDTask\.git\objects\8b\f55994ab33df3e09fe4e0d96dfdea4eb3accb3</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\98\0bf4ec42c9e37f1fcd2a5b78b10112ad29eb9d">
        <Link>addons\GDTask\.git\objects\98\0bf4ec42c9e37f1fcd2a5b78b10112ad29eb9d</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\9e\5add8261e4a18ca72cf7333efa7b49fd9140c9">
        <Link>addons\GDTask\.git\objects\9e\5add8261e4a18ca72cf7333efa7b49fd9140c9</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\a5\989c25def1df490b97803c33076cfecfbd4bfb">
        <Link>addons\GDTask\.git\objects\a5\989c25def1df490b97803c33076cfecfbd4bfb</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\a6\99c4a72f7eb15a59c6bb9212c82368e9c1b2c1">
        <Link>addons\GDTask\.git\objects\a6\99c4a72f7eb15a59c6bb9212c82368e9c1b2c1</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\a9\9ed54d822670ff694a2962d446104e67c69378">
        <Link>addons\GDTask\.git\objects\a9\9ed54d822670ff694a2962d446104e67c69378</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\aa\da6bc77eaa5c3eac5b8c0729ae67907367a3b4">
        <Link>addons\GDTask\.git\objects\aa\da6bc77eaa5c3eac5b8c0729ae67907367a3b4</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\ab\9a048dc66545abd63d08a08ed47e57cf0c80c3">
        <Link>addons\GDTask\.git\objects\ab\9a048dc66545abd63d08a08ed47e57cf0c80c3</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\ac\cb364add32927d028dc5e59ada374e45eb100d">
        <Link>addons\GDTask\.git\objects\ac\cb364add32927d028dc5e59ada374e45eb100d</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\b2\b0141ef8817909b2f92f9d962ca7739f626be7">
        <Link>addons\GDTask\.git\objects\b2\b0141ef8817909b2f92f9d962ca7739f626be7</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\b3\5736b08669fa2809398c8a569028d507990fb5">
        <Link>addons\GDTask\.git\objects\b3\5736b08669fa2809398c8a569028d507990fb5</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\b3\ec36cd3862560836a146e4a82be016755e9be3">
        <Link>addons\GDTask\.git\objects\b3\ec36cd3862560836a146e4a82be016755e9be3</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\b4\d6749d124f8d8c28ce88a5f5a294a38ec8d273">
        <Link>addons\GDTask\.git\objects\b4\d6749d124f8d8c28ce88a5f5a294a38ec8d273</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\ba\06dc57cf323597cb5e4a2db81d0f7b4b85dd5d">
        <Link>addons\GDTask\.git\objects\ba\06dc57cf323597cb5e4a2db81d0f7b4b85dd5d</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\c1\e6faa27d72bb4632ad02706c5ec8cfdb2ee1f2">
        <Link>addons\GDTask\.git\objects\c1\e6faa27d72bb4632ad02706c5ec8cfdb2ee1f2</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\c7\681e284531ee67448215163179da82b426d72c">
        <Link>addons\GDTask\.git\objects\c7\681e284531ee67448215163179da82b426d72c</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\cc\ad739761988123b634fadcc31fbc457d11728c">
        <Link>addons\GDTask\.git\objects\cc\ad739761988123b634fadcc31fbc457d11728c</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\cd\808c56129c2f343438823ed7e6a9dfa8d8e2ac">
        <Link>addons\GDTask\.git\objects\cd\808c56129c2f343438823ed7e6a9dfa8d8e2ac</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\d6\82abd42c261a4e4019f4cf4f9b0429f17c9c2a">
        <Link>addons\GDTask\.git\objects\d6\82abd42c261a4e4019f4cf4f9b0429f17c9c2a</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\d7\22ff9a458802cab4f5651c54cdf2df82c759c3">
        <Link>addons\GDTask\.git\objects\d7\22ff9a458802cab4f5651c54cdf2df82c759c3</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\d9\843d531e3d4358662e368b9985545d572af42e">
        <Link>addons\GDTask\.git\objects\d9\843d531e3d4358662e368b9985545d572af42e</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\dd\1fddc980c9fd04eb25eb41ad037b7fdb1650ff">
        <Link>addons\GDTask\.git\objects\dd\1fddc980c9fd04eb25eb41ad037b7fdb1650ff</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\e0\72998f5692d54503792bbe1cf260a44187b8f0">
        <Link>addons\GDTask\.git\objects\e0\72998f5692d54503792bbe1cf260a44187b8f0</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\e3\162fd2dff9009c361acc6c058de398d407dab7">
        <Link>addons\GDTask\.git\objects\e3\162fd2dff9009c361acc6c058de398d407dab7</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\e6\b8b134c2392c37ec8686a6f7e8267277193f9e">
        <Link>addons\GDTask\.git\objects\e6\b8b134c2392c37ec8686a6f7e8267277193f9e</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\e7\6e5f4492b226f3a8670166eed2fab9578e557b">
        <Link>addons\GDTask\.git\objects\e7\6e5f4492b226f3a8670166eed2fab9578e557b</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\e9\6b71b12cf731d95016ec3cfaf2fe958e0ae672">
        <Link>addons\GDTask\.git\objects\e9\6b71b12cf731d95016ec3cfaf2fe958e0ae672</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\ed\f6df319e55b1f38bf97b54a09a18895d37da29">
        <Link>addons\GDTask\.git\objects\ed\f6df319e55b1f38bf97b54a09a18895d37da29</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\objects\f2\0b81e787177473bc15e6db99a64053e2d7a217">
        <Link>addons\GDTask\.git\objects\f2\0b81e787177473bc15e6db99a64053e2d7a217</Link>
      </Content>
      <Content Include="..\..\addons\GDTask\.git\refs\heads\master">
        <Link>addons\GDTask\.git\refs\heads\master</Link>
      </Content>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="..\..\addons\GDTask\.git\objects\info\">
        <Link>addons\GDTask\.git\objects\info</Link>
      </Folder>
      <Folder Include="..\..\addons\GDTask\.git\objects\pack\">
        <Link>addons\GDTask\.git\objects\pack</Link>
      </Folder>
      <Folder Include="..\..\addons\GDTask\.git\refs\tags\">
        <Link>addons\GDTask\.git\refs\tags</Link>
      </Folder>
    </ItemGroup>
</Project>