<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Precompilation" />
    <Folder Include="Scenes" />
    <Folder Include="Scripts\Game" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Scripts\Build\Generated\**" />
    <Compile Remove="Scripts\Precompilation\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Scripts\Build\Generated\**" />
    <EmbeddedResource Remove="Scripts\Precompilation\**" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="Scripts\Prebuild\Schema\test.ts" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Scripts\Prebuild\main.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>