<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>

    <Configurations>ExportDebug;ExportRelease</Configurations>
    <Platforms>AnyCPU;x64;arm64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lamar" Version="15.0.0"/>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0"/>
    <PackageReference Include="Serilog" Version="4.3.0"/>
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    <PackageReference Include="System.Text.Json" Version="9.0.5"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Remove="test/"/>
    <EmbeddedResource Remove="test/**"/>

    <Folder Remove="addons/"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TeamSports/TeamSports.csproj"/>
    <EmbeddedResource Include="../TeamSports/lib/**"/>

    <ProjectReference Include="../TeamSports.Adaptors.Godot/TeamSports.Adaptors.Godot.csproj"/>
    <EmbeddedResource Include="../TeamSports.Adaptors.Godot/lib/**"/>

    <Compile Include="addons/**/*.cs"/>

    <!-- Include `prebuild` generated sources -->
    <Compile Include="src/prebuild/packages/generate-json/.build/dist/csharp/**/*.cs"/>
    <Compile Remove="test\**"/>
  </ItemGroup>

  <!-- Environment constants -->
  <Choose>
    <When Condition="'$(Configuration)' == 'ExportDebug'">
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);DEVELOPMENT;DEBUG</DefineConstants>
      </PropertyGroup>
    </When>

    <!-- TODO -->
    <When Condition="'$(Configuration)' == 'Staging'">
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);STAGING;DEBUG;RELEASE</DefineConstants>
      </PropertyGroup>
    </When>

    <When Condition="'$(Configuration)' == 'ExportRelease'">
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);PRODUCTION;RELEASE</DefineConstants>
        <Optimize>true</Optimize>
      </PropertyGroup>
    </When>

    <Otherwise>
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);DEVELOPMENT;DEBUG</DefineConstants>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <Choose>
    <When Condition="
      $(DefineConstants.Contains('GODOT_PC')) And
      $(DefineConstants.Contains('DEBUG'))">
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);IMGUI</DefineConstants>
      </PropertyGroup>
    </When>
  </Choose>

  <!-- IMGUI -->
  <Choose>
    <When Condition="$(DefineConstants.Contains('IMGUI'))">
      <ItemGroup>
        <PackageReference Include="ImGui.NET" Version="1.91.0.1"/>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <Compile Remove="addons/imgui-godot/**"/>
      </ItemGroup>
    </Otherwise>
  </Choose>
</Project>
