<Project Sdk="Godot.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>Corpo.Adapters.TeamSports</RootNamespace>

    <Configurations>ExportDebug;ExportStaging;ExportRelease;Debug;Release</Configurations>
    <Platforms>AnyCPU;x64;arm64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0"/>
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../TeamSports/TeamSports.csproj"/>
    <EmbeddedResource Include="../../../TeamSports/TeamSports.csproj"/>

    <ProjectReference Include="../../../TeamSports.Adapters.Godot/TeamSports.Adapters.Godot.csproj"/>
    <EmbeddedResource Include="../../../TeamSports.Adapters.Godot/TeamSports.Adapters.Godot.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="lib\Game\ICorpoStartable.cs.uid"/>
    <Content Include="lib\Screens\ICorpoDebugScreen.cs.uid"/>
    <Content Include="lib\Screens\ICorpoScreen.cs.uid"/>
    <Content Include="lib\Screens\ICorpoScreenBindable.cs.uid"/>
    <Content Include="lib\Screens\ICorpoScreenService.cs.uid"/>
    <Content Include="lib\Screens\ICorpoScreenWrapper.cs.uid"/>
  </ItemGroup>
</Project>
